name: Add 30,000 XP

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  add-xp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add 30,000 XP
        run: |
          echo "⏳ Waiting 10 seconds..."
          sleep 10
          echo "📤 Sending XP request for 30,000 XP..."
          RESPONSE=$(curl --ssl-no-revoke -s -X POST https://api.duolingopro.net/request \
            -H "Authorization: Bearer ${{ secrets.DUOLINGO_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"gain_type": "xp", "amount": 50000}')
          echo "📨 Response from server:"
          echo "$RESPONSE"
